# Site settings
title: Brandmine
email: randal@brandmine.io
description: Amplifying leading consumer brands of the BRICS+
# Change this line
baseurl: "" # Empty for local development

# Then once it works locally, change back to this for GitHub Pages deployment:
# baseurl: "/brandmine-site" # For GitHub Pages project sites, this is often the repository name
url: "https://brandmine.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - CNAME
  - vendor
  
# Collections
collections:
  brands:
    output: true
    permalink: /:collection/:path/
  tags:
    output: true
    permalink: /:collection/:path/
  insights:
    output: true
    permalink: /:collection/:path/
  styleguide:
    output: true
    permalink: /styleguide/:path/
    
    
# Default front matter
defaults:
  # Global defaults
  - scope:
      path: ""
    values:
      layout: default
  
  # Language defaults for pages
  - scope:
      path: "pages/en"
    values:
      lang: en
  - scope:
      path: "pages/ru"
    values:
      lang: ru
  - scope:
      path: "pages/zh"
    values:
      lang: zh

  # Post language defaults
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      show_author: true
      show_date: true
      show_time: false
      permalink: /en/:categories/:year/:month/:day/:title/
  - scope:
      path: "_posts/ru"
      type: "posts"
    values:
      layout: "post"
      lang: "ru"
      show_author: true
      show_date: true
      show_time: false
      permalink: /ru/:categories/:year/:month/:day/:title/
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      layout: "post"
      lang: "zh"
      show_author: true
      show_date: true
      show_time: false
      permalink: /zh/:categories/:year/:month/:day/:title/

  # Brand defaults by language
  - scope:
      path: "_brands/en"
      type: "brands"
    values:
      layout: "brand"
      lang: "en"
  - scope:
      path: "_brands/ru"
      type: "brands"
    values:
      layout: "brand"
      lang: "ru"
  - scope:
      path: "_brands/zh"
      type: "brands"
    values:
      layout: "brand"
      lang: "zh"

  # Tag language defaults
  - scope:
      path: "_tags/en"
      type: "tags"
    values:
      layout: "tag"
      lang: "en"
  - scope:
      path: "_tags/ru"
      type: "tags"
    values:
      layout: "tag"
      lang: "ru"
  - scope:
      path: "_tags/zh"
      type: "tags"
    values:
      layout: "tag"
      lang: "zh"

# Insights
  - scope:
      path: "_insights/en"
      type: "insights"
    values:
      layout: "insight"
      lang: "en"
  - scope:
      path: "_insights/ru"
      type: "insights"
    values:
      layout: "insight"
      lang: "ru"
  - scope:
      path: "_insights/zh"
      type: "insights"
    values:
      layout: "insight"
      lang: "zh"

# Style Guide Configuration
styleguide:
  enabled: true
  sections:
    - name: Foundations
      items:
        - name: Brand Identity
          path: /en/styleguide/foundations/brand-identity/
        - name: Colors
          path: /en/styleguide/foundations/colors/
        - name: Typography
          path: /en/styleguide/foundations/typography/
        - name: Spacing
          path: /en/styleguide/foundations/spacing/
        - name: Layouts
          path: /en/styleguide/foundations/layouts/
    - name: Components
      items:
        - name: Hero Panels
          path: /en/styleguide/components/hero-panels/
        - name: Buttons
          path: /en/styleguide/components/buttons/
        - name: Cards
          path: /en/styleguide/components/cards/
        - name: Forms
          path: /en/styleguide/components/forms/
        - name: Text Components
          path: /en/styleguide/components/text/
    - name: Patterns
      items:
        - name: Navigation
          path: /en/styleguide/patterns/navigation/
        - name: Multilingual
          path: /en/styleguide/patterns/multilingual/
        - name: Content Display
          path: /en/styleguide/patterns/content-display/
        - name: Image Handling
          path: /en/styleguide/patterns/image-handling/
        - name: Tags
          path: /en/styleguide/patterns/tags/