# Site settings
title: Brandmine
email: randal@brandmine.io
description: Amplifying consumer brands of the BRICS+
# Change this line
baseurl: "" # Empty for local development

# Then once it works locally, change back to this for GitHub Pages deployment:
# baseurl: "/brandmine-site" # For GitHub Pages project sites, this is often the repository name
url: "https://brandmine.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - CNAME
  - vendor
  
# Collections
collections:
  brands:
    output: true
    permalink: /:collection/:path/
    
# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "pages/en"
    values:
      lang: en
  - scope:
      path: "pages/ru"
    values:
      lang: ru
  - scope:
      path: "pages/zh"
    values:
      lang: zh

# Blog settings
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  # Add defaults for posts
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "_posts/ru"
      type: "posts"
    values:
      layout: "post"
      lang: "ru"
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      layout: "post"
      lang: "zh"
  # Add defaults for tags
  - scope:
      path: "_tags"
      type: "tags"
    values:
      layout: "tag"