# Site settings
title: Brandmine
email: randal@brandmine.io
description: Amplifying leading consumer brands of the BRICS+
# Change this line
baseurl: "" # Empty for local development

# Then once it works locally, change back to this for GitHub Pages deployment:
# baseurl: "/brandmine-site" # For GitHub Pages project sites, this is often the repository name
url: "https://brandmine.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - CNAME
  - vendor
  
# Collections
collections:
  brands:
    output: true
    permalink: /:collection/:path/
  tags:
    output: true
    permalink: /:collection/:path/
    
# Default front matter
defaults:
  # Global defaults
  - scope:
      path: ""
    values:
      layout: default
  
  # Language defaults for pages
  - scope:
      path: "pages/en"
    values:
      lang: en
  - scope:
      path: "pages/ru"
    values:
      lang: ru
  - scope:
      path: "pages/zh"
    values:
      lang: zh

  # Post language defaults
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      show_author: true
      show_date: true
      show_time: false
      permalink: /en/:categories/:year/:month/:day/:title/
  - scope:
      path: "_posts/ru"
      type: "posts"
    values:
      layout: "post"
      lang: "ru"
      show_author: true
      show_date: true
      show_time: false
      permalink: /ru/:categories/:year/:month/:day/:title/
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      layout: "post"
      lang: "zh"
      show_author: true
      show_date: true
      show_time: false
      permalink: /zh/:categories/:year/:month/:day/:title/

  # Tag language defaults
  - scope:
      path: "_tags/en"
      type: "tags"
    values:
      layout: "tag"
      lang: "en"
  - scope:
      path: "_tags/ru"
      type: "tags"
    values:
      layout: "tag"
      lang: "ru"
  - scope:
      path: "_tags/zh"
      type: "tags"
    values:
      layout: "tag"
      lang: "zh"