dimensions:
  sectors:
    display_name: "Sectors"
    items:
      - slug: wine
        order: 1
      - slug: natural-beauty
        order: 2
      - slug: gourmet-foods
        order: 3
      - slug: artisanal-spirits
        order: 4
      - slug: hotels-resorts
        order: 5
      - slug: artisan-ceramics
        order: 6
      - slug: artisan-confectionery
        order: 7
      - slug: cured-meats
        order: 8
      - slug: fashion-accessories
        order: 9
      - slug: fermented-dairy
        order: 10
      - slug: halal-foods
        order: 11
      - slug: honey-bee-products
        order: 12
      - slug: jewelry-watches
        order: 13
      - slug: mineral-waters
        order: 14
      - slug: natural-supplements
        order: 15
      - slug: specialty-cheeses
        order: 16

  markets:
    display_name: "Markets"
    items:
      - slug: brazil
        country_code: br
        order: 1
      - slug: russia
        country_code: ru
        order: 2
      - slug: india
        country_code: in
        order: 3
      - slug: china
        country_code: cn
        order: 4
      - slug: south-africa
        country_code: za
        order: 5
      - slug: iran
        country_code: ir
        order: 6
      - slug: egypt
        country_code: eg
        order: 7
      - slug: ethiopia
        country_code: et
        order: 8
      - slug: uae
        country_code: ae
        order: 9
      - slug: indonesia
        country_code: id
        order: 10
      - slug: mongolia
        country_code: mn
        order: 11
      - slug: malaysia
        country_code: my
        order: 12

  attributes:
    display_name: "Attributes"
    items:
      - slug: founder-led
        order: 1
      - slug: heritage-brand
        order: 2
      - slug: artisanal-excellence
        order: 3
      - slug: sustainability-pioneer
        order: 4
      - slug: innovation-leader
        order: 5
      - slug: cultural-bridge
        order: 6
      - slug: premium-positioning
        order: 7
      - slug: regional-icon
        order: 8

  signals:
    display_name: "Signals"
    items:
      - slug: export-ready
        order: 1
      - slug: franchise-ready
        order: 2
      - slug: investment-ready
        order: 3
      - slug: rapid-growth
        order: 4