#!/bin/bash

# Script to update CSS class names

sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/debug.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/debug.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/debug.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/debug.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/debug.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/debug.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/debug.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/main.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/main.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/main.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/main.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/main.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/main.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/main.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/style.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/style.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/style.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/style.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/style.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/style.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/style.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/styleguide.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/styleguide.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/styleguide.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/styleguide.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/styleguide.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/styleguide.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/styleguide.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/layout/panels.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/layout/header.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/layout/header.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/layout/header.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/layout/header.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/layout/header.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/layout/header.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/layout/header.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/layout/footer.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/manifest/collections.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/manifest/pages.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/manifest/layout.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/manifest/components.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/team.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/team.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/team.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/team.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/team.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/team.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/team.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/solutions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/image.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/image.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/image.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/image.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/image.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/image.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/image.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/text.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/text.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/text.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/text.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/text.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/text.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/text.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/forms.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/forms.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/forms.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/forms.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/forms.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/forms.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/forms.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/buttons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/layouts.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/cards/cards.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/search/search-box.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/search/search-filter.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/insights/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/home.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/home.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/home.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/home.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/home.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/home.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/home.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/search.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/search.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/search.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/search.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/search.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/search.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/search.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-page.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/brands.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/404.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/404.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/404.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/404.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/404.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/404.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/404.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/about.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/about.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/about.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/about.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/about.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/about.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/about.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/discovery.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/tokens/grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/tokens/tokens.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/tokens/icons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/base/typography.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/base/typography.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/base/typography.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/base/typography.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/base/typography.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/base/typography.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/base/typography.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_site/assets/css/base/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./_site/assets/css/base/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./_site/assets/css/base/layout.css
sed -i '' 's/tag--/dimension--/g' ./_site/assets/css/base/layout.css
sed -i '' 's/__tag/__dimension/g' ./_site/assets/css/base/layout.css
sed -i '' 's/-tag/-dimension/g' ./_site/assets/css/base/layout.css
sed -i '' 's/tag__/dimension__/g' ./_site/assets/css/base/layout.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./_archive/tags.css
sed -i '' 's/\.tag_/.dimension_/g' ./_archive/tags.css
sed -i '' 's/\.tag-/.dimension-/g' ./_archive/tags.css
sed -i '' 's/tag--/dimension--/g' ./_archive/tags.css
sed -i '' 's/__tag/__dimension/g' ./_archive/tags.css
sed -i '' 's/-tag/-dimension/g' ./_archive/tags.css
sed -i '' 's/tag__/dimension__/g' ./_archive/tags.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/debug.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/debug.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/debug.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/debug.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/debug.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/debug.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/debug.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/main.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/main.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/main.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/main.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/main.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/main.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/main.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/styleguide.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/styleguide.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/styleguide.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/styleguide.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/styleguide.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/styleguide.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/styleguide.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/layout/panels.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/layout/panels.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/layout/panels.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/layout/panels.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/layout/panels.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/layout/panels.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/layout/panels.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/layout/header.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/layout/header.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/layout/header.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/layout/header.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/layout/header.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/layout/header.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/layout/header.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/layout/footer.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/layout/footer.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/layout/footer.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/layout/footer.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/layout/footer.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/layout/footer.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/layout/footer.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/manifest/collections.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/manifest/collections.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/manifest/collections.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/manifest/collections.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/manifest/collections.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/manifest/collections.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/manifest/collections.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/manifest/pages.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/manifest/pages.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/manifest/pages.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/manifest/pages.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/manifest/pages.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/manifest/pages.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/manifest/pages.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/manifest/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/manifest/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/manifest/layout.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/manifest/layout.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/manifest/layout.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/manifest/layout.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/manifest/layout.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/manifest/components.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/manifest/components.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/manifest/components.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/manifest/components.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/manifest/components.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/manifest/components.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/manifest/components.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/team.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/team.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/team.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/team.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/team.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/team.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/team.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/solutions.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/solutions.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/solutions.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/solutions.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/solutions.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/solutions.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/solutions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/image.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/image.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/image.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/image.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/image.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/image.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/image.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/text.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/text.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/text.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/text.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/text.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/text.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/text.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/forms.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/forms.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/forms.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/forms.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/forms.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/forms.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/forms.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/mobile-fixes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/buttons.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/buttons.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/buttons.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/buttons.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/buttons.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/buttons.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/buttons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/layouts.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/layouts.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/layouts.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/layouts.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/layouts.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/layouts.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/layouts.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/cards/insight-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/cards/brand-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/cards/cards.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/cards/cards.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/cards/cards.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/cards/cards.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/cards/cards.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/cards/cards.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/cards/cards.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/navigation/navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/search/search-box.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/search/search-box.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/search/search-box.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/search/search-box.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/search/search-box.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/search/search-box.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/search/search-box.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/search/search-filter.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/dimension/dimension.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/components/dimension/dimension-list.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/insights/insights-feed.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/insights/insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/insights/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/brands/featured-brand.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/collections/dimensions/dimensions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/home.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/home.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/home.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/home.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/home.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/home.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/home.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/search.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/search.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/search.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/search.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/search.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/search.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/search.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-page.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/brands.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/brands.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/brands.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/brands.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/brands.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/brands.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/brands.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/404.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/404.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/404.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/404.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/404.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/404.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/404.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/about.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/about.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/about.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/about.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/about.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/about.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/about.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/insights.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/insights.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/insights.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/insights.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/discovery-hub.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/discovery.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/discovery.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/discovery.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/discovery.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/discovery.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/discovery.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/discovery.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/tokens/grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/tokens/grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/tokens/grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/tokens/grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/tokens/grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/tokens/grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/tokens/grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/tokens/tokens.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/tokens/tokens.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/tokens/tokens.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/tokens/tokens.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/tokens/tokens.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/tokens/tokens.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/tokens/tokens.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/tokens/icons.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/tokens/icons.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/tokens/icons.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/tokens/icons.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/tokens/icons.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/tokens/icons.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/tokens/icons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/base/typography.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/base/typography.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/base/typography.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/base/typography.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/base/typography.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/base/typography.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/base/typography.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css/base/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css/base/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css/base/layout.css
sed -i '' 's/tag--/dimension--/g' ./assets/css/base/layout.css
sed -i '' 's/__tag/__dimension/g' ./assets/css/base/layout.css
sed -i '' 's/-tag/-dimension/g' ./assets/css/base/layout.css
sed -i '' 's/tag__/dimension__/g' ./assets/css/base/layout.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/debug.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/debug.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/debug.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/debug.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/debug.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/debug.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/debug.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/main.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/main.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/main.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/main.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/main.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/main.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/main.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/styleguide.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/styleguide.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/styleguide.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/styleguide.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/styleguide.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/styleguide.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/styleguide.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/layout/panels.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/layout/header.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/layout/header.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/layout/header.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/layout/header.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/layout/header.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/layout/header.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/layout/header.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/layout/footer.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/manifest/collections.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/manifest/pages.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/manifest/layout.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/manifest/components.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/team.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/team.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/team.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/team.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/team.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/team.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/team.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/solutions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/image.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/image.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/image.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/image.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/image.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/image.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/image.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/text.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/text.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/text.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/text.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/text.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/text.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/text.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/forms.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/forms.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/forms.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/forms.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/forms.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/forms.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/forms.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/mobile-fixes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/buttons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/layouts.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/carousels/featured-brands-carousel.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/cards/insight-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/cards/brand-card.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/cards/cards.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/navigation/discovery-navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/navigation/navigation.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/search/search-box.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/search/search-filter.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/dimension/dimension.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/dimension/dimension-cloud.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/dimension/discovery-dimensions-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/dimension/discovery-tooltips.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/components/dimension/dimension-list.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/insights/insights-feed.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/insights/insights-grid-categories.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/insights/insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/insights/latest-insights-grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/insights/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/brands/featured-brand.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/collections/dimensions/dimensions.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/home.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/home.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/home.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/home.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/home.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/home.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/home.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/search.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/search.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/search.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/search.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/search.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/search.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/search.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-page.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/brands.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/404.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/404.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/404.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/404.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/404.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/404.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/404.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/about.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/about.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/about.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/about.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/about.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/about.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/about.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/insights.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/discovery-hub.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/discovery.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-specific/discover-attributes.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-specific/discover-markets.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-specific/russian-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-specific/discover-signals.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/pages/dimension-specific/discover-sectors.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/tokens/grid.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/tokens/tokens.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/tokens/icons.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/base/typography.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/base/typography.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/base/typography.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/base/typography.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/base/typography.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/base/typography.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/base/typography.css
sed -i '' 's/\.tag([^a-zA-Z0-9_-])/.dimension\1/g' ./assets/css-backup/base/layout.css
sed -i '' 's/\.tag_/.dimension_/g' ./assets/css-backup/base/layout.css
sed -i '' 's/\.tag-/.dimension-/g' ./assets/css-backup/base/layout.css
sed -i '' 's/tag--/dimension--/g' ./assets/css-backup/base/layout.css
sed -i '' 's/__tag/__dimension/g' ./assets/css-backup/base/layout.css
sed -i '' 's/-tag/-dimension/g' ./assets/css-backup/base/layout.css
sed -i '' 's/tag__/dimension__/g' ./assets/css-backup/base/layout.css
