name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Generate map data
        run: npm run generate-map-data

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      # ✅ New Step: Configure Bundler for Robust CI Installs
      - name: Configure Bundler
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local deployment true
          bundle config set --local without 'development'

      - name: Install Ruby dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
